executionOrder:
  continueOnFailure: false
  flowsOrder:
    - 01-onboarding.yaml
    - 02-login.yaml
    - 03-tab-navigation.yaml
    - 04-create-alarm.yaml
    - 05-voice-management.yaml
    - 06-profile-dropdown.yaml
    - 07-message-tab.yaml
    - 08-code-register.yaml
    - 09-alarm-voice-toggle.yaml
    - 10-home-character.yaml
    - 11-alarm-edit-delete.yaml
    - 12-subscription.yaml
    - 13-library-delete.yaml
