import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, FontSize, FontFamily } from '../constants/theme';
import type { ThemeColors } from '../hooks/useTheme';

export function createPeopleStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing.md,
      paddingBottom: Spacing.sm,
    },
    title: {
      fontSize: FontSize.hero,
      fontFamily: FontFamily.bold,
      color: colors.text,
    },
    addRow: {
      flexDirection: 'row',
      paddingHorizontal: Spacing.lg,
      paddingBottom: Spacing.md,
      gap: Spacing.sm,
    },
    addInput: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: BorderRadius.md,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      fontSize: FontSize.md,
      color: colors.text,
      minHeight: 44,
    },
    addBtn: {
      backgroundColor: colors.primary,
      borderRadius: BorderRadius.md,
      paddingHorizontal: Spacing.lg,
      justifyContent: 'center',
      minHeight: 44,
    },
    addBtnDisabled: {
      opacity: 0.4,
    },
    addBtnText: {
      color: '#FFF',
      fontFamily: FontFamily.semibold,
      fontSize: FontSize.md,
    },
    segmentRow: {
      flexDirection: 'row',
      paddingHorizontal: Spacing.lg,
      marginBottom: Spacing.sm,
      gap: Spacing.xs,
    },
    segment: {
      flex: 1,
      paddingVertical: Spacing.sm,
      alignItems: 'center',
      borderBottomWidth: 2,
      borderBottomColor: 'transparent',
    },
    segmentActive: {
      borderBottomColor: colors.primary,
    },
    segmentText: {
      fontSize: FontSize.md,
      color: colors.textSecondary,
      fontFamily: FontFamily.medium,
    },
    segmentTextActive: {
      color: colors.primary,
      fontFamily: FontFamily.semibold,
    },
    list: {
      paddingHorizontal: Spacing.lg,
      paddingBottom: 100,
    },
    personCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: BorderRadius.lg,
      padding: Spacing.md,
      marginBottom: Spacing.md,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 6,
      elevation: 2,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.primaryLight,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: Spacing.md,
    },
    avatarText: {
      fontSize: FontSize.lg,
      fontFamily: FontFamily.bold,
      color: colors.primaryDark,
    },
    personInfo: {
      flex: 1,
    },
    personName: {
      fontSize: FontSize.md,
      fontFamily: FontFamily.semibold,
      color: colors.text,
    },
    personEmail: {
      fontSize: FontSize.sm,
      color: colors.textSecondary,
      marginTop: 2,
    },
    lastSeen: {
      fontSize: FontSize.xs,
      color: colors.textTertiary,
      fontFamily: FontFamily.regular,
      marginTop: 2,
    },
    familyAlarmBtn: {
      backgroundColor: colors.primary,
      borderRadius: BorderRadius.lg,
      paddingVertical: Spacing.md,
      alignItems: 'center',
      marginTop: Spacing.md,
      minHeight: 48,
      justifyContent: 'center',
    },
    familyAlarmBtnText: {
      color: '#FFF',
      fontSize: FontSize.md,
      fontFamily: FontFamily.semibold,
    },
    removeBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.surfaceVariant,
      justifyContent: 'center',
      alignItems: 'center',
    },
    removeBtnText: {
      fontSize: FontSize.sm,
      color: colors.textTertiary,
    },
    acceptBtn: {
      backgroundColor: colors.primary,
      borderRadius: BorderRadius.md,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      minHeight: 36,
      justifyContent: 'center',
    },
    acceptBtnText: {
      color: '#FFF',
      fontFamily: FontFamily.semibold,
      fontSize: FontSize.sm,
    },
    inviteSection: {
      marginTop: Spacing.lg,
      paddingTop: Spacing.md,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    inviteSectionTitle: {
      fontSize: FontSize.lg,
      fontFamily: FontFamily.semibold,
      color: colors.text,
      marginBottom: Spacing.sm,
    },
    inviteGenerateBtn: {
      backgroundColor: colors.primaryDark,
      borderRadius: BorderRadius.lg,
      paddingVertical: Spacing.md,
      alignItems: 'center',
      minHeight: 48,
      justifyContent: 'center',
    },
    inviteList: {
      marginTop: Spacing.md,
    },
    inviteListTitle: {
      fontSize: FontSize.sm,
      fontFamily: FontFamily.semibold,
      color: colors.textSecondary,
      marginBottom: Spacing.xs,
    },
    inviteCard: {
      backgroundColor: colors.surface,
      borderRadius: BorderRadius.lg,
      padding: Spacing.md,
      marginBottom: Spacing.md,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 6,
      elevation: 2,
    },
    inviteCode: {
      fontSize: FontSize.xl,
      fontFamily: FontFamily.bold,
      color: colors.text,
      letterSpacing: 4,
      textAlign: 'center',
    },
    inviteExpiry: {
      fontSize: FontSize.xs,
      color: colors.textTertiary,
      textAlign: 'center',
      marginTop: Spacing.xs,
    },
    inviteActions: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: Spacing.sm,
      marginTop: Spacing.sm,
    },
    inviteShareBtn: {
      backgroundColor: colors.primary,
      borderRadius: BorderRadius.md,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      minHeight: 36,
      justifyContent: 'center',
    },
    inviteShareBtnText: {
      color: '#FFF',
      fontFamily: FontFamily.semibold,
      fontSize: FontSize.sm,
    },
    inviteRevokeBtn: {
      backgroundColor: colors.surfaceVariant,
      borderRadius: BorderRadius.md,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      minHeight: 36,
      justifyContent: 'center',
    },
    inviteRevokeBtnText: {
      color: colors.textSecondary,
      fontFamily: FontFamily.semibold,
      fontSize: FontSize.sm,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: Spacing.xl,
    },
    emptyEmoji: {
      fontSize: 48,
      marginBottom: Spacing.md,
    },
    emptyText: {
      fontSize: FontSize.md,
      color: colors.textSecondary,
      textAlign: 'center',
    },
    emptyHint: {
      fontSize: FontSize.sm,
      color: colors.textTertiary,
      textAlign: 'center',
      marginTop: Spacing.xs,
    },
    coupleContainer: {
      flex: 1,
      paddingBottom: 100,
    },
  });
}
